remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-remote-theme


title: AMY (2015) -  Short Film - Analysis
description: A Rithin Parker Joseph's film's analysis â€” By Kartik Kashyap
